on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

name: "Release on github and send email"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Push to release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "app-release.apk"
          tag: v1.0.${{github.run_number}}
          token: ${{ secrets.PUBLIC_REPO   }}

      - name: Get Release apk and Send Email
        run: | 
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/latest"
          echo "APK Released: $RELEASE_URL"
          curl --location 'https://api.mailgun.net/v3/salaryontime.com/messages' \
            --header 'Authorization: Basic YXBpOjM1NGRkNjZhNjllN2UzZDVjNDc0NzE5NWRiNTVhM2RkLWFjM2Q1Zjc0LWQ3ODEwZWU3' \
            --form 'from="info@salaryontime.com"' \
            --form 'to="megha@salaryontime.com"' \
            --form "text=Latest APK URL: $RELEASE_URL" \
            --form 'subject="Latest Build HRMS app"'


      # - name: Get Release apk and Send Email
      #   run: | 
      #     RELEASE_URL="https://github.com/${{ github.repository }}/releases/latest"
      #     echo "APK Released: $RELEASE_URL"
      #     curl --location 'https://api.mailgun.net/v3/salaryontime.com/messages' \
      #       --header 'Authorization: Basic YXBpOjM1NGRkNjZhNjllN2UzZDVjNDc0NzE5NWRiNTVhM2RkLWFjM2Q1Zjc0LWQ3ODEwZWU3' \
      #       --form 'from="info@salaryontime.com"' \
      #       # --form 'to="arvind@salaryontime.com", "bhavish@salaryontime.com", "megha@salaryontime.com", "alam@salaryontime.com", "ahsutosh@salaryontime.com", "ishu@salaryontime.com", "ajit@salaryontime.com"' \
      #       --form 'to="arvind@salaryontime.com"' \
      #       --form 'to="megha@salaryontime.com"' \
      #       # --form 'to="bhavish@salaryontime.com"' \
      #       --form "text=Latest APK URL: $RELEASE_URL" \
      #       --form 'subject="Latest Build HRMS app"'
